core/urls.py
from django.contrib import admin
from django.urls import path, include
from tiendaApi import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teslo_shop.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
    #api
    path('productosapi/', views.ProductoApis, name='productosapi'),
    path('productosListApi/',views.ProductoApi, name='productosApi'),
    path('productosDetailApi/<int:pk>/', views.ProductoApiDetail, name='productosapidetail'),
]

teslo_shop/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from .tallas import tallas
from django.utils.crypto import get_random_string


# Create your models here.

class Producto(models.Model):
    nombre = models.CharField(max_length=50 , verbose_name='Nombre del producto')
    descripcion = models.CharField(max_length=200, verbose_name='Descripción del producto')
    precio = models.IntegerField( verbose_name='Precio del producto')
    talla = models.CharField(max_length=2, choices=tallas, verbose_name='Talla del producto')
    stock = models.IntegerField( default=0, verbose_name='Stock del producto')
    
    imagen = models.ImageField(upload_to='Productos/', null=True,blank=True, verbose_name='Imagen del producto')
       
    class Meta:
        db_table = 'Producto'
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

    def __str__(self):
        return self.nombre
    
class Venta(models.Model):
    codigo = models.CharField(max_length=10, unique=True, verbose_name='Código de venta')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(verbose_name='Cantidad')
    nombre_comprador = models.CharField(max_length=100, verbose_name='Nombre del comprador')
    fecha_venta = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de venta')
    correo = models.EmailField(verbose_name='Correo de contacto',null=True)
    direccion_envio = models.CharField(max_length=255, verbose_name='Dirección de envío',null=True)
    rut = models.CharField(max_length=12, verbose_name='RUT',null=True)

    def save(self, *args, **kwargs):
        if not self.codigo:
            self.codigo = get_random_string(length=8)  # Generar código aleatorio si no se proporciona uno
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Venta {self.codigo} - {self.nombre_comprador}"

templates/ventas/add_ventas.html
{% extends 'teslo/base.html' %}

{% block title %}Teslo - Generar Venta{% endblock %}
{% load crispy_forms_tags %}

{% block contenido %}
<div class="bg-light mt-5 rounded p-2">
  <h2 class="mt-2 text-center">Crear venta</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary text-center">Crear</button>
    <a href="{% url 'ventas' %}" class="btn btn-secondary">Cancelar</a>
  </form>
</div>

{% endblock %}
```

templates/ventas/compra_exitosa.html
{% extends 'teslo/base.html' %}

{% block content %}
{% load static %}

<div class="container mt-5">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>¡Compra exitosa!</strong> Tu compra se ha realizado con éxito.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
</div>
{% endblock %}

templates/ventas/crear_venta.html
{% extends 'teslo/base.html' %}

{% block title %}Teslo - Comprar{% endblock %}

{% block contenido %}
<h1 class="text-white text-center fw-bolder mt-4">Formulario Compra</h1>
<div class="container mt-4">
  <div class="row ">
    <div class="col-md-6">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="producto" value="{{ producto.id }}">
        <div class="mb-3">
          <label for="id_cantidad" class="form-label text-white">Cantidad:</label>
          {{ form.cantidad }}
        </div>
        <div class="mb-3">
          <label for="id_nombre_comprador" class="form-label text-white">Nombre del Comprador:</label>
          {{ form.nombre_comprador }}
        </div>
        <div class="mb-3">
          <label for="id_correo" class="form-label text-white">Correo de contacto:</label>
          {{ form.correo }}
        </div>
        <div class="mb-3">
          <label for="id_direccion_envio" class="form-label text-white">Dirección de envío:</label>
          {{ form.direccion_envio }}
        </div>
        <div class="mb-3">
          <label for="id_rut" class="form-label text-white">RUT:</label>
          {{ form.rut }}
        </div>
        <input type="submit" value="Comprar" class="btn btn-success">
      </form>
    </div>
    <div class="col-md-6">
      <h2 class="text-white  mt-2 mb-3">Detalles del Producto</h2>
      <div class="productos-card">
        <img class="image-product" src="{{ producto.imagen.url }}" alt="">
        <div class="producto-card-info text-wrap">
          <h3 class="text-white text-center fw-bolder mt-3">{{ producto.nombre }}</h3>
          <p class="text-white text-center">{{ producto.descripcion }}</p>
          <p class="precio text-white text-center fw-bolder">${{ producto.precio }}</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/ventas/delete_ventas.html
{% extends 'teslo/base.html' %}

{% block title %}Teslo - Descartar Venta{% endblock %}

{% block contenido %}
<div class="bg-light mt-5 rounded p-2">
  <h2 class="">¿Estas seguro que desea eliminar la venta {{ venta.id }}?</h2>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'usuarios' %}" class="btn btn-secondary">Cancelar</a>
  </form>
</div>
{% endblock %}

templates/ventas/edit_ventas.html
{% extends 'teslo/base.html' %}

{% block title %}Teslo - Editar Venta{% endblock %}
{% load crispy_forms_tags %}

{% block contenido %}

<div class="bg-light mt-4 rounded p-3">
  <h2 >Editar Venta</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary ">Guardar Cambios</button>
    <a href="{% url 'usuarios' %}" class="btn btn-secondary">Cancelar</a>
  </form>
</div>
{% endblock %}

templates/ventas/list.html
{% extends 'teslo/base.html' %}

{% block title %}Teslo - Lista de Ventas{% endblock %}

{% block contenido %}
<div class="text-center mt-5">
  <button class="btn btn-primary"><a class="text-white text-decoration-none"  href="{% url 'mantenedores' %}">Volver</a></button>
</div>

{% if messages %}
<div class="text-center d-flex justify-content-center  align-items-center mt-2 ">
  <ul class="messages alert alert-success text-decoration-none ">
    {% for message in messages %}
      <li{% if message.tags %} class="text-decoration-none {{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
</div>
{% endif %}

<div class="container">
  <div class="row">
    <div class="col-md-12  mt-4">
      <div class="card bg-light">
        <div class="card-body">
          <div class="row">
            <div class="col-md-12">
              <div class="d-flex justify-content-between align-items-center">
                <h4>Listado de Ventas</h4>
                <form method="get" action="#" class="w-50">
                  <div class="input-group">
                    <input id="search-input" type="text" name="q" class="form-control" placeholder="Buscar por nombre de producto" value="{{ request.GET.q }}">
                    <div class="input-group-append ms-2">
                      <button class="btn btn-primary" type="submit">Buscar</button>
                    </div>
                  </div>
                </form>
                <a href="{% url 'agregar_venta' %}" class="btn btn-success m">Agregar Venta</a>
              </div>
            </div>
          </div>
          <div class="row mt-4">
            <div class="col-md-12">
              <table class="table table-striped table-hover">
                <thead>
                  <tr>
                    <th>Código de Venta</th>
                    <th>Producto</th>
                    <th>Cantidad</th>
                    <th>Nombre del Comprador</th>
                    <th>Correo</th> <!-- Agregar el campo correo -->
                    <th>Dirección de Envío</th> <!-- Agregar el campo dirección de envío -->
                    <th>RUT</th> <!-- Agregar el campo RUT -->
                    <th>Fecha de Venta</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tbody>
                  {% for venta in ventas %}
                  <tr>
                    <td>{{ venta.codigo }}</td>
                    <td>{{ venta.producto.nombre }}</td>
                    <td>{{ venta.cantidad }}</td>
                    <td>{{ venta.nombre_comprador }}</td>
                    <td>{{ venta.correo }}</td> <!-- Campo correo -->
                    <td>{{ venta.direccion_envio }}</td> <!-- Campo dirección de envío -->
                    <td>{{ venta.rut }}</td> <!-- Campo RUT -->
                    <td>{{ venta.fecha_venta }}</td>
                    <td>
                      <a href="{% url 'editar_venta' venta.id %}" class="btn btn-info">
                        <i class="fas fa-eye"></i> Editar
                      </a>
                      <a href="{% url 'eliminar_venta' venta.id %}" class="btn btn-danger">
                        <i class="fas fa-trash-alt"></i> Eliminar
                      </a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  setTimeout(function() {
    var messages = document.getElementsByClassName("messages")[0];
    if (messages) {
      messages.style.display = "none";
    }
  }, 3000);  // Cambia 4000 a la cantidad de milisegundos que deseas (por ejemplo, 5000 = 5 segundos)
</script>

{% endblock %}